### ISSUE TITLE
Musicians: Manage Posts

### ISSUE THREAD

**Issue by simonv3** [funmusicplace/blackbird#10]
* [x] Create
* [x] Read
* [x] Update
* [x] Soft Delete (part of #19) 
* [x] Embed track in post
* [ ] Mark posts as private or as public

**Comment by simonv3** [comment]
Look at this https://dev.to/patarapolw/securely-embed-youtube-and-other-iframe-elements-in-markdown-2hoc and https://github.com/remarkjs/react-markdown#security for security stuff on allowing iframes in markdown.
