### ISSUE TITLE
Musicians: Manage Music

### ISSUE THREAD

**Issue by simonv3** [funmusicplace/blackbird#9]
* [x] Create
* [x] Read
* [x] Update
* [x] Soft Delete
* [x] Add and manage tracks on albums `3`
  * [x] Mark tracks as previews: I think here it makes sense to default tracks to be previewable and to let artists un-toggle that them.  
* [x] Add album details
* [x] Add cover to album
* [x] Add price to album
* [x] Upload music to minIO
